USE eCommerce_DB
GO

IF OBJECT_ID('ROLES', 'U') IS NULL
BEGIN
    CREATE TABLE ROLES (
        IdRol INT PRIMARY KEY IDENTITY(1,1),
        Nombre VARCHAR(50) NOT NULL UNIQUE
    );
END
GO

IF OBJECT_ID('USUARIOS_ROLES', 'U') IS NULL
BEGIN
    CREATE TABLE USUARIOS_ROLES (
        IdUsuario INT NOT NULL,
        IdRol INT NOT NULL,

        PRIMARY KEY (IdUsuario, IdRol),
        FOREIGN KEY(IdUsuario) REFERENCES USUARIOS(IdUsuario),
        FOREIGN KEY(IdRol) REFERENCES ROLES(IdRol)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM ROLES WHERE Nombre = 'Cliente')
    INSERT INTO ROLES (Nombre) VALUES ('Cliente');

IF NOT EXISTS (SELECT 1 FROM ROLES WHERE Nombre = 'Vendedor')
    INSERT INTO ROLES (Nombre) VALUES ('Vendedor');

IF NOT EXISTS (SELECT 1 FROM ROLES WHERE Nombre = 'Admin')
    INSERT INTO ROLES (Nombre) VALUES ('Admin');
GO
