CREATE DATABASE eCommerce_DB
GO

USE eCommerce_DB
GO

CREATE TABLE CATEGORIAS (
    IdCategoria INT PRIMARY KEY IDENTITY(1,1),

    Nombre VARCHAR(50) NOT NULL,
    Activo BIT NOT NULL DEFAULT 1
);

CREATE TABLE MARCAS (
    IdMarca INT PRIMARY KEY IDENTITY(1,1),

    Nombre VARCHAR(50) NOT NULL,
    Activo BIT NOT NULL DEFAULT 1

);

CREATE TABLE FORMASPAGO (
    IdFormaPago INT PRIMARY KEY IDENTITY(1,1),

    Descripcion VARCHAR(50) NOT NULL,
    Activo BIT NOT NULL DEFAULT 1
);

CREATE TABLE FORMASENTREGA (
    IdFormaEntrega INT PRIMARY KEY IDENTITY(1,1),

    Descripcion VARCHAR(50) NOT NULL,
    Activo BIT NOT NULL DEFAULT 1
);

CREATE TABLE ESTADOSPEDIDO (
    IdEstadoPedido INT PRIMARY KEY IDENTITY(1,1),

    Descripcion VARCHAR(50) NOT NULL
);

CREATE TABLE USUARIOS (
    IdUsuario INT PRIMARY KEY IDENTITY(1,1),

    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Dni VARCHAR(15) NOT NULL,
    FechaNacimiento DATE NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Telefono VARCHAR(30) NOT NULL,
    Clave VARCHAR(100) NOT NULL,
    Rol VARCHAR(50) NOT NULL,
    Activo BIT NOT NULL
);

CREATE TABLE DIRECCIONES(
    IdDireccion INT PRIMARY KEY IDENTITY(1,1),

    IdUsuario INT NOT NULL,

    Descripcion VARCHAR(50) NULL,
    Calle VARCHAR(100) NOT NULL,
    Altura INT NOT NULL,
    Localidad VARCHAR(50) NOT NULL,
    Provincia VARCHAR(50) NOT NULL,
    Cp VARCHAR(15) NOT NULL,
    Observaciones VARCHAR(500) NULL,

    FOREIGN KEY(IdUsuario) REFERENCES USUARIOS(IdUsuario)
);

CREATE TABLE PRODUCTOS(
    IdProducto INT PRIMARY KEY IDENTITY(1,1),

    IdCategoria INT NOT NULL,
    IdMarca INT NOT NULL,

    Sku VARCHAR(30) NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Descripcion VARCHAR(500) NULL,
    Precio DECIMAL(10,2) NOT NULL,
    Stock INT NOT NULL,
    Activo BIT NOT NULL,

    FOREIGN KEY(IdCategoria) REFERENCES CATEGORIAS(IdCategoria),
    FOREIGN KEY(IdMarca) REFERENCES MARCAS(IdMarca)
);

CREATE TABLE IMAGENES(
    IdImagen INT PRIMARY KEY IDENTITY(1,1),

    IdProducto INT NOT NULL,

    Nombre VARCHAR(100) NOT NULL,
    UrlImagen VARCHAR(500) NOT NULL,

    FOREIGN KEY(IdProducto) REFERENCES PRODUCTOS(IdProducto)
);

CREATE TABLE PEDIDOS(
    IdPedido INT PRIMARY KEY IDENTITY(1,1),

    IdUsuario INT NOT NULL,
    IdDireccion INT NULL,
    IdFormaPago INT NOT NULL,
    IdFormaEntrega INT NOT NULL,
    IdEstadoPedido INT NOT NULL,

    FechaCreacion DATETIME NOT NULL,
    FechaEntrega DATETIME NULL,
    Total DECIMAL(10,2) NOT NULL,

    FOREIGN KEY(IdUsuario) REFERENCES USUARIOS(IdUsuario),
    FOREIGN KEY(IdDireccion) REFERENCES DIRECCIONES(IdDireccion),
    FOREIGN KEY(IdFormaPago) REFERENCES FORMASPAGO(IdFormaPago),
    FOREIGN KEY(IdFormaEntrega) REFERENCES FORMASENTREGA(IdFormaEntrega),
    FOREIGN KEY(IdEstadoPedido) REFERENCES ESTADOSPEDIDO(IdEstadoPedido)
);

CREATE TABLE DETALLESPEDIDO(
    IdDetallePedido INT PRIMARY KEY IDENTITY(1,1),

    IdPedido INT NOT NULL,
    IdProducto INT NOT NULL,

    Cantidad INT NOT NULL,
    PrecioUnitario DECIMAL(10,2) NOT NULL,
    Subtotal DECIMAL(10,2) NOT NULL,

    FOREIGN KEY(IdPedido) REFERENCES PEDIDOS(IdPedido),
    FOREIGN KEY(IdProducto) REFERENCES PRODUCTOS(IdProducto)
);
